/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eef2ff', 100: '#e0e7ff', 200: '#c7d2fe', 300: '#a5b4fc',
          400: '#818cf8', 500: '#5B5CEB', 600: '#4f46e5', 700: '#4338ca',
        },
        accent: {
          green: '#22C55E', violet: '#7C3AED', amber: '#F59E0B',
          rose: '#EF4444', blue: '#3B82F6', cyan: '#06B6D4',
          pink: '#EC4899', neon: '#00f0ff',
        },
      },
      fontFamily: {
        sans: ['DM Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        heading: ['Outfit', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SF Mono', 'monospace'],
      },
      borderRadius: { '4xl': '2rem' },
      boxShadow: {
        'glow-sm': '0 0 20px var(--primary-glow)',
        'glow': '0 0 30px var(--primary-glow)',
        'glow-lg': '0 0 50px var(--primary-glow)',
        'glow-cyan': '0 0 24px rgba(0, 240, 255, 0.12)',
        'glow-cyan-lg': '0 0 48px rgba(0, 240, 255, 0.18)',
        'glow-success': '0 0 30px var(--glow-success)',
        'glow-danger': '0 0 30px var(--glow-danger)',
        'glow-warning': '0 0 30px var(--glow-warning)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.04), inset 0 1px 0 rgba(255, 255, 255, 0.06)',
        'glass-lg': '0 16px 48px rgba(0, 0, 0, 0.06), inset 0 1px 0 rgba(255, 255, 255, 0.08)',
        'hud': '0 4px 24px rgba(0, 0, 0, 0.2), 0 0 1px rgba(0, 240, 255, 0.15)',
        'hud-lg': '0 8px 40px rgba(0, 0, 0, 0.3), 0 0 2px rgba(0, 240, 255, 0.2)',
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease forwards',
        'slide-up': 'slideUp 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-down': 'slideDown 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'scale-in': 'scaleIn 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'glow-pulse': 'glowPulse 3s ease-in-out infinite',
        'gradient-shift': 'gradientShift 4s ease infinite',
        'float': 'float 20s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'page-enter': 'pageEnter 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'badge-pulse': 'badgePulse 2s ease-in-out infinite',
        'aurora': 'aurora 30s ease-in-out infinite',
        'heartbeat': 'heartbeat 1.5s ease-in-out infinite',
        'skeleton': 'skeleton 1.4s ease infinite',
        'spin-slow': 'spin 3s linear infinite',
        'border-glow': 'borderPulse 2s ease-in-out infinite',
        'hud-pulse': 'hudPulse 4s ease-in-out infinite',
        'scan': 'scanLineY 8s linear infinite',
        'mesh-drift': 'meshDrift 25s ease-in-out infinite',
        'grid-pulse': 'gridPulse 4s ease-in-out infinite',
        'float-up': 'floatUp 6s ease-in-out infinite',
        'bell-bounce': 'bellBounce 1s ease-in-out',
        'shake': 'shake 0.5s ease-in-out',
        'success-pulse': 'successPulse 0.6s ease-out',
        'scale-bounce': 'scaleBounce 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp: { from: { transform: 'translateY(20px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        slideDown: { from: { transform: 'translateY(-20px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        scaleIn: { from: { transform: 'scale(0.95)', opacity: '0' }, to: { transform: 'scale(1)', opacity: '1' } },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 20px var(--primary-glow)' },
          '50%': { boxShadow: '0 0 40px var(--primary-glow)' },
        },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        pageEnter: {
          from: { opacity: '0', transform: 'translateY(12px) scale(0.99)', filter: 'blur(4px)' },
          to: { opacity: '1', transform: 'translateY(0) scale(1)', filter: 'blur(0)' },
        },
        badgePulse: { '0%, 100%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.15)' } },
        aurora: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg) scale(1)' },
          '25%': { transform: 'translate(30px, -40px) rotate(5deg) scale(1.05)' },
          '50%': { transform: 'translate(-20px, 30px) rotate(-3deg) scale(0.95)' },
          '75%': { transform: 'translate(35px, 15px) rotate(2deg) scale(1.02)' },
        },
        heartbeat: {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '14%': { transform: 'scale(1.15)' }, '28%': { transform: 'scale(1)' },
          '42%': { transform: 'scale(1.15)' }, '70%': { transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
          '25%': { transform: 'translate(20px, -30px) rotate(5deg)' },
          '50%': { transform: 'translate(-15px, 20px) rotate(-3deg)' },
          '75%': { transform: 'translate(25px, 10px) rotate(2deg)' },
        },
        hudPulse: {
          '0%, 100%': { boxShadow: '0 0 15px rgba(0, 240, 255, 0.04)' },
          '50%': { boxShadow: '0 0 25px rgba(0, 240, 255, 0.08)' },
        },
      },
    },
  },
  plugins: [],
}
