services:
  - type: web
    name: payment-reconciliation-engine
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://payflow_admin:PBnSlVfFcX6bWU55lJWdbdRh21GmAlR0@dpg-d9jnk4ou01pc73944ot0-a/payment_reconciliation_engine
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
    healthCheckPath: /health
    autoDeploy: true
